# -*- coding: utf-8 -*-
"""Official Full Messages Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4dCzJTBsOc5zCfeRroL-_ZTa119U6Wr
"""

# Install spacy/transformers
!pip install --upgrade pip
!pip install -U spacy spacy-curated-transformers
!python -m spacy download en_core_web_trf

# Use GPU
import torch
import spacy
if torch.cuda.is_available():
    spacy.require_gpu()
else:
    spacy.prefer_gpu()
nlp = spacy.load("en_core_web_trf")

# Load in datasets

import pandas as pd
import numpy as np
df_hawk = pd.read_csv("https://raw.githubusercontent.com/refbank/refbank-import/refs/heads/main/harmonized_data/hawkins2020_characterizing_cued/messages.csv")
df_boyce = pd.read_csv("https://raw.githubusercontent.com/refbank/refbank-import/refs/heads/main/harmonized_data/boyce2024_interaction/messages.csv")

num_new_cols = 768

# Add symmantic definition in 768 vector space for each message to inputed dataframe
def addEmbeddings(df_in):
  lst_of_list_with_embeds = []

  # Go through each message
  texts = df_in["text"].tolist()  # list of all texts
  docs = list(nlp.pipe(texts, batch_size=16))
  for doc in docs:
      tensor = doc._.trf_data.last_hidden_layer_state
      dat = tensor.data
      means = np.mean(dat, axis=0)
      lst_of_list_with_embeds.append(means)
  embeddings_list_cpu = []

  # Convert to datafrane
  for embed_lst in lst_of_list_with_embeds:
      if hasattr(embed_lst, "detach"):
          embeddings_list_cpu.append(embed_lst.detach().cpu().numpy())
      elif hasattr(embed_lst, "get"):
          embeddings_list_cpu.append(embed_lst.get())
      else:
          embeddings_list_cpu.append(embed_lst)
  embeddings_array = np.vstack(embeddings_list_cpu).astype(np.float64)
  new_df = pd.DataFrame(embeddings_array,
                        columns=[f"dim space: {num}" for num in range(1, num_new_cols + 1)],
                        index=df_in.index)


  df_out = pd.concat([df_in, new_df], axis=1)
  df_out["message_irrelevant"] = df_out["message_irrelevant"].fillna(False).astype(bool)
  return df_out

df_hawk_ed = addEmbeddings(df_hawk)
df_boyce_ed = addEmbeddings(df_boyce)

# Save dataframes
df_hawk_ed.to_csv("Hawkins 768 edited 3.csv")
df_boyce_ed.to_csv("Boyce 768 edited 3.csv")

# Load in dataframes, if necesary
# import pandas as pd
# import numpy as np
# df_hawk_ed = pd.read_csv("Hawkins 768 edited 3.csv")
# df_boyce_ed = pd.read_csv("Boyce 768 edited 3.csv")
# num_new_cols = 768

# Analyze class imbalances
print(df_hawk_ed["message_irrelevant"].value_counts(normalize=True))
print(df_boyce_ed["message_irrelevant"].value_counts(normalize=True))

# Fit models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


cols = [f"dim space: {i}" for i in range(1, num_new_cols + 1)] # 768 columns with embeddings

X_train = df_hawk_ed[cols]
y_train = df_hawk_ed["message_irrelevant"]
X_test = df_boyce_ed[cols]
y_test = df_boyce_ed["message_irrelevant"]

RFC_model = RandomForestClassifier()
RFC_model.fit(X_train, y_train)

LR_model = LogisticRegression(max_iter=15000)
LR_model.fit(X_train, y_train)

# Have models make predictions and print out results

RFC_pred = (RFC_model.predict_proba(X_test)[:,1])
RFC_pred_bool = (RFC_pred >= 0.5).astype(bool) # Can adjust the 0.5 value to get better recall on 'message_relevant' class, but doesn't affect ROC curve
print("RFC")
print(classification_report(y_test, RFC_pred_bool))

print("LR")
LR_pred = (LR_model.predict_proba(X_test)[:,1])
LR_pred_bool = (LR_pred  > 0.5).astype(bool) # Can adjust the 0.5 value to get better recall on 'message_relevant' class, but doesn't affect ROC curve
print(classification_report(y_test, LR_pred_bool))

# I decided to comment out KNN because it did poorly
# print("KNN")
# KNN_pred = (KNN_model.predict_proba(X_test)[:,1])
# KNN_pred_bool = (KNN_pred  > 0.5).astype(bool)
# print(classification_report(y_test, KNN_pred_bool))

# Build graphs and save results

from sklearn import metrics
from sklearn.metrics import RocCurveDisplay
import matplotlib.pyplot as plt
import numpy as np

LR_fpr, LR_tpr, LR_thresholds = metrics.roc_curve(y_test, LR_pred)
LR_auc = round(metrics.auc(LR_fpr, LR_tpr), 3)
plt.plot(LR_fpr, LR_tpr, label=f"Logistic Regression, AUC={LR_auc}")

RFC_fpr, RFC_tpr, RFC_thresholds = metrics.roc_curve(y_test, RFC_pred)
RFC_auc = round(metrics.auc(RFC_fpr, RFC_tpr), 3)
plt.plot(RFC_fpr, RFC_tpr, label=f"Random Forest Classifier, AUC={RFC_auc}")

# I decided to comment out KNN because it did poorly
# KNN_fpr, KNN_tpr, KNN_thresholds = metrics.roc_curve(y_test, KNN_pred)
# KNN_auc = round(metrics.auc(KNN_fpr, KNN_tpr), 3)
# plt.plot(KNN_fpr, KNN_tpr, label=f"KNN, AUC={KNN_auc}")

plt.plot([0, 1], [0, 1], color='red', linestyle='--', label='Random Selection, AUC=0.5')

plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.legend()
plt.savefig("Train_Hawk Test_Boyce ROC Curve (5).png")